/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author usuario
 */
public class V_CityList_Admin extends javax.swing.JFrame {
    V_Perfil_Modificar vistaModPerfil;
    V_Inicio vistaInicio;
    V_HotelList vistaHoteles;
    /**
     * Creates new form V_CityList
     */
    public V_CityList_Admin(V_Perfil_Modificar vistaModPerfil, V_Inicio vistaInicial,V_HotelList vistaHoteles) {
        initComponents();
        this.vistaModPerfil = vistaModPerfil;
        this.vistaInicio = vistaInicial;
        this.vistaHoteles = vistaHoteles;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        BienvenidoMensage = new javax.swing.JLabel();
        Perfil = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ProfilePic = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        BuscadorCiudad = new javax.swing.JTextField();
        CiudadesDisponibles = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Scroll_BGPanel = new javax.swing.JPanel();
        ScrollBox = new javax.swing.JPanel();
        Ciudad_InfoBox1 = new javax.swing.JPanel();
        Ciudad_Pic1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ZonaTP = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ranking = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        NombreCiudadTP2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        DescripcionCiudad = new javax.swing.JTextPane();
        ModificarBtn1 = new javax.swing.JButton();
        EliminarBtn1 = new javax.swing.JButton();
        Ciudad_InfoBox5 = new javax.swing.JPanel();
        Ciudad_Pic5 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        ZonaTP4 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        Ranking4 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        NombreCiudadTP6 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        DescripcionCiudad4 = new javax.swing.JTextPane();
        ModificarBtn5 = new javax.swing.JButton();
        EliminarBtn2 = new javax.swing.JButton();
        Ciudad_InfoBox6 = new javax.swing.JPanel();
        Ciudad_Pic6 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        ZonaTP5 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        Ranking5 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        NombreCiudadTP7 = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        DescripcionCiudad5 = new javax.swing.JTextPane();
        ModificarBtn6 = new javax.swing.JButton();
        EliminarBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(204, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(720, 80));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText(" 123 Viajes C.A");

        BienvenidoMensage.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BienvenidoMensage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoMensage.setText("Bienvenido/a");

        Perfil.setBackground(new java.awt.Color(153, 255, 255));
        Perfil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Perfil.setMnemonic('3');
        Perfil.setText("Perfil");
        Perfil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 255, 255));
        Salir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Salir.setMnemonic('3');
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setText("ProfilePic");
        ProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Background.setMaximumSize(new java.awt.Dimension(720, 480));
        Background.setMinimumSize(new java.awt.Dimension(720, 480));

        BuscadorCiudad.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        BuscadorCiudad.setForeground(new java.awt.Color(102, 102, 102));
        BuscadorCiudad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        BuscadorCiudad.setText("Ciudad");
        BuscadorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorCiudadActionPerformed(evt);
            }
        });

        CiudadesDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CiudadesDisponibles.setText("Ciudades disponibles");

        BuscarBtn.setBackground(new java.awt.Color(204, 255, 255));
        BuscarBtn.setText("Buscar");
        BuscarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Scroll_BGPanel.setBackground(new java.awt.Color(255, 255, 255));
        Scroll_BGPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        Scroll_BGPanel.setOpaque(false);
        Scroll_BGPanel.setLayout(new java.awt.GridLayout());

        ScrollBox.setBackground(new java.awt.Color(255, 255, 255));
        ScrollBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        ScrollBox.setOpaque(false);

        Ciudad_InfoBox1.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox1.setAutoscrolls(true);
        Ciudad_InfoBox1.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox1.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox1.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic1.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic1.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic1.setText("Pic");
        Ciudad_Pic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox1.add(Ciudad_Pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP.setText("Zona");
        jScrollPane3.setViewportView(ZonaTP);

        Ciudad_InfoBox1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking.setForeground(new java.awt.Color(153, 153, 153));
        Ranking.setText("20/123");
        jScrollPane4.setViewportView(Ranking);

        Ciudad_InfoBox1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP2.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP2.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP2.setText("Nombre");
        NombreCiudadTP2.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane5.setViewportView(NombreCiudadTP2);

        Ciudad_InfoBox1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad.setText("Descripcion");
        jScrollPane6.setViewportView(DescripcionCiudad);

        Ciudad_InfoBox1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ModificarBtn1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarBtn1.setText("Modificar");
        ModificarBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ModificarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtn1ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox1.add(ModificarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 75, 50));

        EliminarBtn1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarBtn1.setText("Eliminar");
        EliminarBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EliminarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtn1ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox1.add(EliminarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 75, 50));

        Ciudad_InfoBox5.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox5.setAutoscrolls(true);
        Ciudad_InfoBox5.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox5.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox5.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic5.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic5.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic5.setText("Pic");
        Ciudad_Pic5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox5.add(Ciudad_Pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP4.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP4.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP4.setText("Zona");
        jScrollPane19.setViewportView(ZonaTP4);

        Ciudad_InfoBox5.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking4.setForeground(new java.awt.Color(153, 153, 153));
        Ranking4.setText("20/123");
        jScrollPane20.setViewportView(Ranking4);

        Ciudad_InfoBox5.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP6.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP6.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP6.setText("Nombre");
        NombreCiudadTP6.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane21.setViewportView(NombreCiudadTP6);

        Ciudad_InfoBox5.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad4.setText("Descripcion");
        jScrollPane22.setViewportView(DescripcionCiudad4);

        Ciudad_InfoBox5.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ModificarBtn5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarBtn5.setText("Modificar");
        ModificarBtn5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ModificarBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtn5ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox5.add(ModificarBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 75, 50));

        EliminarBtn2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarBtn2.setText("Eliminar");
        EliminarBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EliminarBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtn2ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox5.add(EliminarBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 75, 50));

        Ciudad_InfoBox6.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox6.setAutoscrolls(true);
        Ciudad_InfoBox6.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox6.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox6.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic6.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic6.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic6.setText("Pic");
        Ciudad_Pic6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox6.add(Ciudad_Pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP5.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP5.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP5.setText("Zona");
        jScrollPane23.setViewportView(ZonaTP5);

        Ciudad_InfoBox6.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking5.setForeground(new java.awt.Color(153, 153, 153));
        Ranking5.setText("20/123");
        jScrollPane24.setViewportView(Ranking5);

        Ciudad_InfoBox6.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP7.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP7.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP7.setText("Nombre");
        NombreCiudadTP7.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane25.setViewportView(NombreCiudadTP7);

        Ciudad_InfoBox6.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad5.setText("Descripcion");
        jScrollPane26.setViewportView(DescripcionCiudad5);

        Ciudad_InfoBox6.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ModificarBtn6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarBtn6.setText("Modificar");
        ModificarBtn6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ModificarBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtn6ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox6.add(ModificarBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 75, 50));

        EliminarBtn3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarBtn3.setText("Eliminar");
        EliminarBtn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EliminarBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtn3ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox6.add(EliminarBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 75, 50));

        javax.swing.GroupLayout ScrollBoxLayout = new javax.swing.GroupLayout(ScrollBox);
        ScrollBox.setLayout(ScrollBoxLayout);
        ScrollBoxLayout.setHorizontalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addGroup(ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ciudad_InfoBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad_InfoBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad_InfoBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ScrollBoxLayout.setVerticalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addComponent(Ciudad_InfoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ciudad_InfoBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ciudad_InfoBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1191, Short.MAX_VALUE))
        );

        Scroll_BGPanel.add(ScrollBox);

        jScrollPane1.setViewportView(Scroll_BGPanel);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(BuscadorCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BuscadorCiudad)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorCiudadActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void ModificarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarBtn1ActionPerformed

    private void EliminarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarBtn1ActionPerformed

    private void ModificarBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarBtn5ActionPerformed

    private void EliminarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarBtn2ActionPerformed

    private void ModificarBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarBtn6ActionPerformed

    private void EliminarBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BienvenidoMensage;
    private javax.swing.JTextField BuscadorCiudad;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JPanel Ciudad_InfoBox1;
    private javax.swing.JPanel Ciudad_InfoBox5;
    private javax.swing.JPanel Ciudad_InfoBox6;
    private javax.swing.JLabel Ciudad_Pic1;
    private javax.swing.JLabel Ciudad_Pic5;
    private javax.swing.JLabel Ciudad_Pic6;
    private javax.swing.JLabel CiudadesDisponibles;
    private javax.swing.JTextPane DescripcionCiudad;
    private javax.swing.JTextPane DescripcionCiudad4;
    private javax.swing.JTextPane DescripcionCiudad5;
    private javax.swing.JButton EliminarBtn1;
    private javax.swing.JButton EliminarBtn2;
    private javax.swing.JButton EliminarBtn3;
    private javax.swing.JPanel Header;
    private javax.swing.JButton ModificarBtn1;
    private javax.swing.JButton ModificarBtn5;
    private javax.swing.JButton ModificarBtn6;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JTextPane NombreCiudadTP2;
    private javax.swing.JTextPane NombreCiudadTP6;
    private javax.swing.JTextPane NombreCiudadTP7;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JTextPane Ranking;
    private javax.swing.JTextPane Ranking4;
    private javax.swing.JTextPane Ranking5;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel ScrollBox;
    private javax.swing.JPanel Scroll_BGPanel;
    private javax.swing.JTextPane ZonaTP;
    private javax.swing.JTextPane ZonaTP4;
    private javax.swing.JTextPane ZonaTP5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
