/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class V_CityList extends javax.swing.JFrame {
    V_Perfil_Modificar vistaModPerfil;
    V_Inicio vistaInicio;
    V_HotelList vistaHoteles;
    V_Pago vistaPago;
    /**
     * Creates new form V_CityList
     */
    public V_CityList(V_Perfil_Modificar vistaModPerfil, V_Inicio vistaInicial,V_HotelList vistaHoteles) {
        initComponents();
        this.vistaModPerfil = vistaModPerfil;
        this.vistaInicio = vistaInicial;
        this.vistaHoteles = vistaHoteles;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        BienvenidoMensage = new javax.swing.JLabel();
        Perfil = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ProfilePic = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        BuscadorCiudad = new javax.swing.JTextField();
        CiudadesDisponibles = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Scroll_BGPanel = new javax.swing.JPanel();
        ScrollBox = new javax.swing.JPanel();
        Ciudad_InfoBox1 = new javax.swing.JPanel();
        Ciudad_Pic1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ZonaTP = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ranking = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        NombreCiudadTP2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        DescripcionCiudad = new javax.swing.JTextPane();
        ReservarBtn1 = new javax.swing.JButton();
        Ciudad_InfoBox2 = new javax.swing.JPanel();
        Ciudad_Pic2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ZonaTP1 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        Ranking1 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        NombreCiudadTP3 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        DescripcionCiudad1 = new javax.swing.JTextPane();
        ReservarBtn2 = new javax.swing.JButton();
        Ciudad_InfoBox3 = new javax.swing.JPanel();
        Ciudad_Pic3 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        ZonaTP2 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        Ranking2 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        NombreCiudadTP4 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        DescripcionCiudad2 = new javax.swing.JTextPane();
        ReservarBtn3 = new javax.swing.JButton();
        Ciudad_InfoBox4 = new javax.swing.JPanel();
        Ciudad_Pic4 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        ZonaTP3 = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        Ranking3 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        NombreCiudadTP5 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        DescripcionCiudad3 = new javax.swing.JTextPane();
        ReservarBtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(204, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(720, 80));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText(" 123 Viajes C.A");

        BienvenidoMensage.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BienvenidoMensage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoMensage.setText("Bienvenido/a");

        Perfil.setBackground(new java.awt.Color(153, 255, 255));
        Perfil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Perfil.setMnemonic('3');
        Perfil.setText("Perfil");
        Perfil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 255, 255));
        Salir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Salir.setMnemonic('3');
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setText("ProfilePic");
        ProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Background.setMaximumSize(new java.awt.Dimension(720, 480));
        Background.setMinimumSize(new java.awt.Dimension(720, 480));

        BuscadorCiudad.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        BuscadorCiudad.setForeground(new java.awt.Color(102, 102, 102));
        BuscadorCiudad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        BuscadorCiudad.setText("Ciudad");
        BuscadorCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscadorCiudadMousePressed(evt);
            }
        });

        CiudadesDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CiudadesDisponibles.setText("Ciudades disponibles");

        BuscarBtn.setBackground(new java.awt.Color(204, 255, 255));
        BuscarBtn.setText("Buscar");
        BuscarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Scroll_BGPanel.setBackground(new java.awt.Color(255, 255, 255));
        Scroll_BGPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        Scroll_BGPanel.setOpaque(false);
        Scroll_BGPanel.setLayout(new java.awt.GridLayout());

        ScrollBox.setBackground(new java.awt.Color(255, 255, 255));
        ScrollBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        ScrollBox.setOpaque(false);

        Ciudad_InfoBox1.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox1.setAutoscrolls(true);
        Ciudad_InfoBox1.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox1.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox1.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic1.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic1.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic1.setText("Pic");
        Ciudad_Pic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox1.add(Ciudad_Pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP.setText("Zona");
        jScrollPane3.setViewportView(ZonaTP);

        Ciudad_InfoBox1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking.setForeground(new java.awt.Color(153, 153, 153));
        Ranking.setText("20/123");
        jScrollPane4.setViewportView(Ranking);

        Ciudad_InfoBox1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP2.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP2.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP2.setText("Nombre");
        NombreCiudadTP2.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane5.setViewportView(NombreCiudadTP2);

        Ciudad_InfoBox1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad.setText("Descripcion");
        jScrollPane6.setViewportView(DescripcionCiudad);

        Ciudad_InfoBox1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ReservarBtn1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ReservarBtn1.setText("Reservar");
        ReservarBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ReservarBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarBtn1MouseClicked(evt);
            }
        });
        ReservarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBtn1ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox1.add(ReservarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 75, 50));

        Ciudad_InfoBox2.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox2.setAutoscrolls(true);
        Ciudad_InfoBox2.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox2.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox2.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic2.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic2.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic2.setText("Pic");
        Ciudad_Pic2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox2.add(Ciudad_Pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP1.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP1.setText("Zona");
        jScrollPane7.setViewportView(ZonaTP1);

        Ciudad_InfoBox2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking1.setForeground(new java.awt.Color(153, 153, 153));
        Ranking1.setText("20/123");
        jScrollPane8.setViewportView(Ranking1);

        Ciudad_InfoBox2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP3.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP3.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP3.setText("Nombre");
        NombreCiudadTP3.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane9.setViewportView(NombreCiudadTP3);

        Ciudad_InfoBox2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad1.setText("Descripcion");
        jScrollPane10.setViewportView(DescripcionCiudad1);

        Ciudad_InfoBox2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ReservarBtn2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ReservarBtn2.setText("Reservar");
        ReservarBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ReservarBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarBtn1MouseClicked(evt);
            }
        });
        ReservarBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBtn2ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox2.add(ReservarBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 75, 50));

        Ciudad_InfoBox3.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox3.setAutoscrolls(true);
        Ciudad_InfoBox3.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox3.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox3.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic3.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic3.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic3.setText("Pic");
        Ciudad_Pic3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox3.add(Ciudad_Pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP2.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP2.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP2.setText("Zona");
        jScrollPane11.setViewportView(ZonaTP2);

        Ciudad_InfoBox3.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking2.setForeground(new java.awt.Color(153, 153, 153));
        Ranking2.setText("20/123");
        jScrollPane12.setViewportView(Ranking2);

        Ciudad_InfoBox3.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP4.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP4.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP4.setText("Nombre");
        NombreCiudadTP4.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane13.setViewportView(NombreCiudadTP4);

        Ciudad_InfoBox3.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad2.setText("Descripcion");
        jScrollPane14.setViewportView(DescripcionCiudad2);

        Ciudad_InfoBox3.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ReservarBtn3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ReservarBtn3.setText("Reservar");
        ReservarBtn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ReservarBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarBtn1MouseClicked(evt);
            }
        });
        ReservarBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBtn3ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox3.add(ReservarBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 75, 50));

        Ciudad_InfoBox4.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_InfoBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox4.setAutoscrolls(true);
        Ciudad_InfoBox4.setMaximumSize(new java.awt.Dimension(50, 32767));
        Ciudad_InfoBox4.setMinimumSize(new java.awt.Dimension(645, 127));
        Ciudad_InfoBox4.setPreferredSize(new java.awt.Dimension(645, 134));
        Ciudad_InfoBox4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_Pic4.setBackground(new java.awt.Color(204, 255, 255));
        Ciudad_Pic4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ciudad_Pic4.setForeground(new java.awt.Color(153, 153, 153));
        Ciudad_Pic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic4.setText("Pic");
        Ciudad_Pic4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ciudad_InfoBox4.add(Ciudad_Pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        ZonaTP3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ZonaTP3.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ZonaTP3.setForeground(new java.awt.Color(153, 153, 153));
        ZonaTP3.setText("Zona");
        jScrollPane15.setViewportView(ZonaTP3);

        Ciudad_InfoBox4.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        Ranking3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ranking3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ranking3.setForeground(new java.awt.Color(153, 153, 153));
        Ranking3.setText("20/123");
        jScrollPane16.setViewportView(Ranking3);

        Ciudad_InfoBox4.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreCiudadTP5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreCiudadTP5.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        NombreCiudadTP5.setForeground(new java.awt.Color(153, 153, 153));
        NombreCiudadTP5.setText("Nombre");
        NombreCiudadTP5.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane17.setViewportView(NombreCiudadTP5);

        Ciudad_InfoBox4.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        DescripcionCiudad3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        DescripcionCiudad3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescripcionCiudad3.setText("Descripcion");
        jScrollPane18.setViewportView(DescripcionCiudad3);

        Ciudad_InfoBox4.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        ReservarBtn4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ReservarBtn4.setText("Reservar");
        ReservarBtn4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ReservarBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarBtn1MouseClicked(evt);
            }
        });
        ReservarBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBtn4ActionPerformed(evt);
            }
        });
        Ciudad_InfoBox4.add(ReservarBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 75, 50));

        javax.swing.GroupLayout ScrollBoxLayout = new javax.swing.GroupLayout(ScrollBox);
        ScrollBox.setLayout(ScrollBoxLayout);
        ScrollBoxLayout.setHorizontalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addGroup(ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ciudad_InfoBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad_InfoBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad_InfoBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad_InfoBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ScrollBoxLayout.setVerticalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addComponent(Ciudad_InfoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ciudad_InfoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ciudad_InfoBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ciudad_InfoBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 771, Short.MAX_VALUE))
        );

        Scroll_BGPanel.add(ScrollBox);

        jScrollPane1.setViewportView(Scroll_BGPanel);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(BuscadorCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BuscadorCiudad)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void ReservarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservarBtn1ActionPerformed

    private void ReservarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservarBtn2ActionPerformed

    private void ReservarBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservarBtn3ActionPerformed

    private void ReservarBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservarBtn4ActionPerformed

    private void BuscadorCiudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorCiudadMousePressed
        // TODO add your handling code here:
    BuscadorCiudad.setText("");
    BuscadorCiudad.setForeground(Color.black);
    }//GEN-LAST:event_BuscadorCiudadMousePressed

    private void ReservarBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservarBtn1MouseClicked
    // TODO add your handling code here:
    vistaPago = new V_Pago();
    vistaPago.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ReservarBtn1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BienvenidoMensage;
    private javax.swing.JTextField BuscadorCiudad;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JPanel Ciudad_InfoBox1;
    private javax.swing.JPanel Ciudad_InfoBox2;
    private javax.swing.JPanel Ciudad_InfoBox3;
    private javax.swing.JPanel Ciudad_InfoBox4;
    private javax.swing.JLabel Ciudad_Pic1;
    private javax.swing.JLabel Ciudad_Pic2;
    private javax.swing.JLabel Ciudad_Pic3;
    private javax.swing.JLabel Ciudad_Pic4;
    private javax.swing.JLabel CiudadesDisponibles;
    private javax.swing.JTextPane DescripcionCiudad;
    private javax.swing.JTextPane DescripcionCiudad1;
    private javax.swing.JTextPane DescripcionCiudad2;
    private javax.swing.JTextPane DescripcionCiudad3;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JTextPane NombreCiudadTP2;
    private javax.swing.JTextPane NombreCiudadTP3;
    private javax.swing.JTextPane NombreCiudadTP4;
    private javax.swing.JTextPane NombreCiudadTP5;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JTextPane Ranking;
    private javax.swing.JTextPane Ranking1;
    private javax.swing.JTextPane Ranking2;
    private javax.swing.JTextPane Ranking3;
    private javax.swing.JButton ReservarBtn1;
    private javax.swing.JButton ReservarBtn2;
    private javax.swing.JButton ReservarBtn3;
    private javax.swing.JButton ReservarBtn4;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel ScrollBox;
    private javax.swing.JPanel Scroll_BGPanel;
    private javax.swing.JTextPane ZonaTP;
    private javax.swing.JTextPane ZonaTP1;
    private javax.swing.JTextPane ZonaTP2;
    private javax.swing.JTextPane ZonaTP3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
