/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author usuario
 */
public class V_HotelList extends javax.swing.JFrame {

    V_Perfil_Modificar vistaModPerfil;
    V_Inicio vistaInicial;

    /**
     * Creates new form V_HotelList
     */
    public V_HotelList(V_Inicio vistaInicial, V_Perfil_Modificar vistaModPerfil) {
        initComponents();
        this.vistaModPerfil = vistaModPerfil;
        this.vistaInicial = vistaInicial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        BienvenidoMensage = new javax.swing.JLabel();
        Perfil = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ProfilePic = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        BuscadorCiudad = new javax.swing.JTextField();
        CiudadesDisponibles = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Scroll_BGPanel = new javax.swing.JPanel();
        ScrollBox = new javax.swing.JPanel();
        Hotel_InfoBox = new javax.swing.JPanel();
        Ver = new javax.swing.JButton();
        InfoHotel = new javax.swing.JTextField();
        Hotel_Pic = new javax.swing.JLabel();
        Hotel_InfoBox2 = new javax.swing.JPanel();
        Ver2 = new javax.swing.JButton();
        InfoHotel2 = new javax.swing.JTextField();
        Hotel_Pic1 = new javax.swing.JLabel();
        Hotel_InfoBox7 = new javax.swing.JPanel();
        Ver7 = new javax.swing.JButton();
        InfoHotel7 = new javax.swing.JTextField();
        Hotel_Pic5 = new javax.swing.JLabel();
        Hotel_InfoBox8 = new javax.swing.JPanel();
        Ver8 = new javax.swing.JButton();
        InfoHotel8 = new javax.swing.JTextField();
        Hotel_Pic6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(204, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(720, 80));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText(" 123 Viajes C.A");

        BienvenidoMensage.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BienvenidoMensage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoMensage.setText("Bienvenido/a");

        Perfil.setBackground(new java.awt.Color(153, 255, 255));
        Perfil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Perfil.setMnemonic('3');
        Perfil.setText("Perfil");
        Perfil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 255, 255));
        Salir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Salir.setMnemonic('3');
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setText("ProfilePic");
        ProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(720, 480));
        Background.setMinimumSize(new java.awt.Dimension(720, 480));

        BuscadorCiudad.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        BuscadorCiudad.setForeground(new java.awt.Color(102, 102, 102));
        BuscadorCiudad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        BuscadorCiudad.setText("Playa, montaña, ...");
        BuscadorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorCiudadActionPerformed(evt);
            }
        });

        CiudadesDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CiudadesDisponibles.setText("Hoteles disponibles");

        BuscarBtn.setBackground(new java.awt.Color(204, 255, 255));
        BuscarBtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Scroll_BGPanel.setBackground(new java.awt.Color(255, 255, 255));
        Scroll_BGPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        Scroll_BGPanel.setOpaque(false);
        Scroll_BGPanel.setLayout(new java.awt.GridLayout(1, 0));

        ScrollBox.setBackground(new java.awt.Color(255, 255, 255));
        ScrollBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        ScrollBox.setOpaque(false);

        Hotel_InfoBox.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox.setAutoscrolls(true);
        Hotel_InfoBox.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ver.setText("Reservar");
        Ver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });

        InfoHotel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InfoHotel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel.setText("Info Hotel");
        InfoHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotelActionPerformed(evt);
            }
        });

        Hotel_Pic.setBackground(new java.awt.Color(153, 255, 255));
        Hotel_Pic.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic.setText("Pic");
        Hotel_Pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBoxLayout = new javax.swing.GroupLayout(Hotel_InfoBox);
        Hotel_InfoBox.setLayout(Hotel_InfoBoxLayout);
        Hotel_InfoBoxLayout.setHorizontalGroup(
            Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hotel_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Hotel_InfoBoxLayout.setVerticalGroup(
            Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotel_Pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Hotel_InfoBox2.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox2.setAutoscrolls(true);
        Hotel_InfoBox2.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ver2.setText("Reservar");
        Ver2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver2ActionPerformed(evt);
            }
        });

        InfoHotel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InfoHotel2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel2.setText("Info Hotel");
        InfoHotel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotel2ActionPerformed(evt);
            }
        });

        Hotel_Pic1.setBackground(new java.awt.Color(153, 255, 255));
        Hotel_Pic1.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic1.setText("Pic");
        Hotel_Pic1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBox2Layout = new javax.swing.GroupLayout(Hotel_InfoBox2);
        Hotel_InfoBox2.setLayout(Hotel_InfoBox2Layout);
        Hotel_InfoBox2Layout.setHorizontalGroup(
            Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBox2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hotel_Pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Hotel_InfoBox2Layout.setVerticalGroup(
            Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBox2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotel_Pic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Hotel_InfoBox7.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox7.setAutoscrolls(true);
        Hotel_InfoBox7.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ver7.setText("Reservar");
        Ver7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ver7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver7ActionPerformed(evt);
            }
        });

        InfoHotel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InfoHotel7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel7.setText("Info Hotel");
        InfoHotel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotel7ActionPerformed(evt);
            }
        });

        Hotel_Pic5.setBackground(new java.awt.Color(153, 255, 255));
        Hotel_Pic5.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic5.setText("Pic");
        Hotel_Pic5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBox7Layout = new javax.swing.GroupLayout(Hotel_InfoBox7);
        Hotel_InfoBox7.setLayout(Hotel_InfoBox7Layout);
        Hotel_InfoBox7Layout.setHorizontalGroup(
            Hotel_InfoBox7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBox7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hotel_Pic5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel7, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Hotel_InfoBox7Layout.setVerticalGroup(
            Hotel_InfoBox7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBox7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBox7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotel_Pic5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBox7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel7, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Hotel_InfoBox8.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox8.setAutoscrolls(true);
        Hotel_InfoBox8.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ver8.setText("Reservar");
        Ver8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Ver8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver8ActionPerformed(evt);
            }
        });

        InfoHotel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InfoHotel8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel8.setText("Info Hotel");
        InfoHotel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotel8ActionPerformed(evt);
            }
        });

        Hotel_Pic6.setBackground(new java.awt.Color(153, 255, 255));
        Hotel_Pic6.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic6.setText("Pic");
        Hotel_Pic6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBox8Layout = new javax.swing.GroupLayout(Hotel_InfoBox8);
        Hotel_InfoBox8.setLayout(Hotel_InfoBox8Layout);
        Hotel_InfoBox8Layout.setHorizontalGroup(
            Hotel_InfoBox8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBox8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hotel_Pic6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel8, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Hotel_InfoBox8Layout.setVerticalGroup(
            Hotel_InfoBox8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBox8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBox8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hotel_Pic6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBox8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel8, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout ScrollBoxLayout = new javax.swing.GroupLayout(ScrollBox);
        ScrollBox.setLayout(ScrollBoxLayout);
        ScrollBoxLayout.setHorizontalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hotel_InfoBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Hotel_InfoBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Hotel_InfoBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Hotel_InfoBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ScrollBoxLayout.setVerticalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addComponent(Hotel_InfoBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        Scroll_BGPanel.add(ScrollBox);

        jScrollPane1.setViewportView(Scroll_BGPanel);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(BuscadorCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BuscadorCiudad)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 482));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorCiudadActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerActionPerformed

    private void InfoHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotelActionPerformed

    private void Ver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver2ActionPerformed

    private void InfoHotel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotel2ActionPerformed

    private void Ver7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver7ActionPerformed

    private void InfoHotel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotel7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotel7ActionPerformed

    private void Ver8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver8ActionPerformed

    private void InfoHotel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotel8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotel8ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BienvenidoMensage;
    private javax.swing.JTextField BuscadorCiudad;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JLabel CiudadesDisponibles;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Hotel_InfoBox;
    private javax.swing.JPanel Hotel_InfoBox2;
    private javax.swing.JPanel Hotel_InfoBox4;
    private javax.swing.JPanel Hotel_InfoBox5;
    private javax.swing.JPanel Hotel_InfoBox6;
    private javax.swing.JPanel Hotel_InfoBox7;
    private javax.swing.JPanel Hotel_InfoBox8;
    private javax.swing.JLabel Hotel_Pic;
    private javax.swing.JLabel Hotel_Pic1;
    private javax.swing.JLabel Hotel_Pic2;
    private javax.swing.JLabel Hotel_Pic3;
    private javax.swing.JLabel Hotel_Pic4;
    private javax.swing.JLabel Hotel_Pic5;
    private javax.swing.JLabel Hotel_Pic6;
    private javax.swing.JTextField InfoHotel;
    private javax.swing.JTextField InfoHotel2;
    private javax.swing.JTextField InfoHotel4;
    private javax.swing.JTextField InfoHotel5;
    private javax.swing.JTextField InfoHotel6;
    private javax.swing.JTextField InfoHotel7;
    private javax.swing.JTextField InfoHotel8;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel ScrollBox;
    private javax.swing.JPanel Scroll_BGPanel;
    private javax.swing.JButton Ver;
    private javax.swing.JButton Ver2;
    private javax.swing.JButton Ver4;
    private javax.swing.JButton Ver5;
    private javax.swing.JButton Ver6;
    private javax.swing.JButton Ver7;
    private javax.swing.JButton Ver8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
