/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author usuario
 */
public class V_HotelList extends javax.swing.JFrame {

    V_Perfil_Modificar vistaModPerfil;
    V_Inicio vistaInicial;

    /**
     * Creates new form V_HotelList
     */
    public V_HotelList(V_Inicio vistaInicial, V_Perfil_Modificar vistaModPerfil) {
        initComponents();
        this.vistaModPerfil = vistaModPerfil;
        this.vistaInicial = vistaInicial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BuscadorCiudad = new javax.swing.JTextField();
        CiudadesDisponibles = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        ScrollBox = new javax.swing.JPanel();
        Hotel_InfoBox = new javax.swing.JPanel();
        Ver = new javax.swing.JButton();
        InfoHotel = new javax.swing.JTextField();
        Ciudad_Pic = new javax.swing.JLabel();
        Hotel_InfoBox1 = new javax.swing.JPanel();
        Ver1 = new javax.swing.JButton();
        InfoHotel1 = new javax.swing.JTextField();
        Ciudad_Pic1 = new javax.swing.JLabel();
        Hotel_InfoBox2 = new javax.swing.JPanel();
        Ver2 = new javax.swing.JButton();
        InfoHotel2 = new javax.swing.JTextField();
        Ciudad_Pic2 = new javax.swing.JLabel();
        Hotel_InfoBox3 = new javax.swing.JPanel();
        Ver3 = new javax.swing.JButton();
        InfoHotel3 = new javax.swing.JTextField();
        Ciudad_Pic3 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        BienvenidoMensage = new javax.swing.JLabel();
        Perfil = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ProfilePic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(720, 480));
        Background.setMinimumSize(new java.awt.Dimension(720, 480));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscadorCiudad.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        BuscadorCiudad.setForeground(new java.awt.Color(102, 102, 102));
        BuscadorCiudad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        BuscadorCiudad.setText("Playa, montaña, ...");
        BuscadorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorCiudadActionPerformed(evt);
            }
        });
        Background.add(BuscadorCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 440, 29));

        CiudadesDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CiudadesDisponibles.setText("Hoteles disponibles");
        Background.add(CiudadesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 128, 29));

        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });
        Background.add(BuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 80, 29));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Hotel_InfoBox.setBackground(new java.awt.Color(204, 204, 204));
        Hotel_InfoBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Hotel_InfoBox.setAutoscrolls(true);
        Hotel_InfoBox.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver.setText("Reservar");
        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });

        InfoHotel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel.setText("Info Hotel");
        InfoHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotelActionPerformed(evt);
            }
        });

        Ciudad_Pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic.setText("Pic");
        Ciudad_Pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBoxLayout = new javax.swing.GroupLayout(Hotel_InfoBox);
        Hotel_InfoBox.setLayout(Hotel_InfoBoxLayout);
        Hotel_InfoBoxLayout.setHorizontalGroup(
            Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ciudad_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Hotel_InfoBoxLayout.setVerticalGroup(
            Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ciudad_Pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Hotel_InfoBox1.setBackground(new java.awt.Color(204, 204, 204));
        Hotel_InfoBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Hotel_InfoBox1.setAutoscrolls(true);
        Hotel_InfoBox1.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver1.setText("Reservar");
        Ver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver1ActionPerformed(evt);
            }
        });

        InfoHotel1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel1.setText("Info Ciudad");
        InfoHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotel1ActionPerformed(evt);
            }
        });

        Ciudad_Pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic1.setText("Pic");
        Ciudad_Pic1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBox1Layout = new javax.swing.GroupLayout(Hotel_InfoBox1);
        Hotel_InfoBox1.setLayout(Hotel_InfoBox1Layout);
        Hotel_InfoBox1Layout.setHorizontalGroup(
            Hotel_InfoBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBox1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ciudad_Pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Hotel_InfoBox1Layout.setVerticalGroup(
            Hotel_InfoBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBox1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ciudad_Pic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Hotel_InfoBox2.setBackground(new java.awt.Color(204, 204, 204));
        Hotel_InfoBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Hotel_InfoBox2.setAutoscrolls(true);
        Hotel_InfoBox2.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver2.setText("Reservar");
        Ver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver2ActionPerformed(evt);
            }
        });

        InfoHotel2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel2.setText("Info Hotel");
        InfoHotel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotel2ActionPerformed(evt);
            }
        });

        Ciudad_Pic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic2.setText("Pic");
        Ciudad_Pic2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBox2Layout = new javax.swing.GroupLayout(Hotel_InfoBox2);
        Hotel_InfoBox2.setLayout(Hotel_InfoBox2Layout);
        Hotel_InfoBox2Layout.setHorizontalGroup(
            Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBox2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ciudad_Pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Hotel_InfoBox2Layout.setVerticalGroup(
            Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBox2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ciudad_Pic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Hotel_InfoBox3.setBackground(new java.awt.Color(204, 204, 204));
        Hotel_InfoBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Hotel_InfoBox3.setAutoscrolls(true);
        Hotel_InfoBox3.setMaximumSize(new java.awt.Dimension(50, 32767));

        Ver3.setText("Reservar");
        Ver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver3ActionPerformed(evt);
            }
        });

        InfoHotel3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InfoHotel3.setText("Info Ciudad");
        InfoHotel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHotel3ActionPerformed(evt);
            }
        });

        Ciudad_Pic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_Pic3.setText("Pic");
        Ciudad_Pic3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Hotel_InfoBox3Layout = new javax.swing.GroupLayout(Hotel_InfoBox3);
        Hotel_InfoBox3.setLayout(Hotel_InfoBox3Layout);
        Hotel_InfoBox3Layout.setHorizontalGroup(
            Hotel_InfoBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotel_InfoBox3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ciudad_Pic3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ver3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Hotel_InfoBox3Layout.setVerticalGroup(
            Hotel_InfoBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotel_InfoBox3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hotel_InfoBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ciudad_Pic3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Hotel_InfoBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InfoHotel3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Ver3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout ScrollBoxLayout = new javax.swing.GroupLayout(ScrollBox);
        ScrollBox.setLayout(ScrollBoxLayout);
        ScrollBoxLayout.setHorizontalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addGroup(ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hotel_InfoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hotel_InfoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hotel_InfoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hotel_InfoBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        ScrollBoxLayout.setVerticalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hotel_InfoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(ScrollBox);

        jScrollPane1.setViewportView(jPanel2);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 661, 300));

        Header.setBackground(new java.awt.Color(204, 255, 255));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText("123 Viajes C.A");

        BienvenidoMensage.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BienvenidoMensage.setText("Bienvenido/a");

        Perfil.setBackground(new java.awt.Color(153, 255, 255));
        Perfil.setMnemonic('3');
        Perfil.setText("Perfil");
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 255, 255));
        Salir.setMnemonic('3');
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setText("ProfilePic");
        ProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Perfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salir))
                    .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Perfil)
                            .addComponent(Salir)))
                    .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 6, -1, -1));

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorCiudadActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerActionPerformed

    private void InfoHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotelActionPerformed

    private void Ver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver1ActionPerformed

    private void InfoHotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotel1ActionPerformed

    private void Ver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver2ActionPerformed

    private void InfoHotel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotel2ActionPerformed

    private void Ver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver3ActionPerformed

    private void InfoHotel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHotel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoHotel3ActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.vistaModPerfil.setVisible(true);
    }//GEN-LAST:event_PerfilActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BienvenidoMensage;
    private javax.swing.JTextField BuscadorCiudad;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JLabel Ciudad_Pic;
    private javax.swing.JLabel Ciudad_Pic1;
    private javax.swing.JLabel Ciudad_Pic2;
    private javax.swing.JLabel Ciudad_Pic3;
    private javax.swing.JLabel CiudadesDisponibles;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Hotel_InfoBox;
    private javax.swing.JPanel Hotel_InfoBox1;
    private javax.swing.JPanel Hotel_InfoBox2;
    private javax.swing.JPanel Hotel_InfoBox3;
    private javax.swing.JTextField InfoHotel;
    private javax.swing.JTextField InfoHotel1;
    private javax.swing.JTextField InfoHotel2;
    private javax.swing.JTextField InfoHotel3;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel ScrollBox;
    private javax.swing.JButton Ver;
    private javax.swing.JButton Ver1;
    private javax.swing.JButton Ver2;
    private javax.swing.JButton Ver3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
