/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author usuario
 */
public class V_HotelList_Admin extends javax.swing.JFrame {

    V_Perfil_Modificar vistaModPerfil;
    V_Inicio vistaInicial;

    /**
     * Creates new form V_HotelList
     */
    public V_HotelList_Admin(V_Inicio vistaInicial, V_Perfil_Modificar vistaModPerfil) {
        initComponents();
        this.vistaModPerfil = vistaModPerfil;
        this.vistaInicial = vistaInicial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        BienvenidoMensage = new javax.swing.JLabel();
        Perfil = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ProfilePic = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        BuscadorCiudad = new javax.swing.JTextField();
        CiudadesDisponibles = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Scroll_BGPanel = new javax.swing.JPanel();
        ScrollBox = new javax.swing.JPanel();
        Hotel_InfoBox3 = new javax.swing.JPanel();
        EliminarBtn3 = new javax.swing.JButton();
        ModificarBtn3 = new javax.swing.JButton();
        Hotel_Pic3 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        EmailHotelTP2 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        TelefonoHotelTP2 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        NombreHotelTP4 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        Hotel_InfoBox1 = new javax.swing.JPanel();
        EliminarBtn1 = new javax.swing.JButton();
        ModificarBtn1 = new javax.swing.JButton();
        Hotel_Pic1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        EmailHotelTP = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TelefonoHotelTP = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        NombreHotelTP2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        Hotel_InfoBox2 = new javax.swing.JPanel();
        EliminarBtn2 = new javax.swing.JButton();
        ModificarBtn2 = new javax.swing.JButton();
        Hotel_Pic2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        EmailHotelTP1 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        TelefonoHotelTP1 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        NombreHotelTP3 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(204, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(720, 80));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText(" 123 Viajes C.A");

        BienvenidoMensage.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BienvenidoMensage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoMensage.setText("Bienvenido/a");

        Perfil.setBackground(new java.awt.Color(153, 255, 255));
        Perfil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Perfil.setMnemonic('3');
        Perfil.setText("Perfil");
        Perfil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 255, 255));
        Salir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Salir.setMnemonic('3');
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setText("ProfilePic");
        ProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(720, 480));
        Background.setMinimumSize(new java.awt.Dimension(720, 480));
        Background.setPreferredSize(new java.awt.Dimension(720, 480));

        BuscadorCiudad.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        BuscadorCiudad.setForeground(new java.awt.Color(102, 102, 102));
        BuscadorCiudad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        BuscadorCiudad.setText("Playa, montaña, ...");
        BuscadorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorCiudadActionPerformed(evt);
            }
        });

        CiudadesDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CiudadesDisponibles.setText("Hoteles disponibles");

        BuscarBtn.setBackground(new java.awt.Color(204, 255, 255));
        BuscarBtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Scroll_BGPanel.setBackground(new java.awt.Color(255, 255, 255));
        Scroll_BGPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        Scroll_BGPanel.setOpaque(false);
        Scroll_BGPanel.setLayout(new java.awt.GridLayout(1, 0));

        ScrollBox.setBackground(new java.awt.Color(255, 255, 255));
        ScrollBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        ScrollBox.setOpaque(false);

        Hotel_InfoBox3.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox3.setAutoscrolls(true);
        Hotel_InfoBox3.setMaximumSize(new java.awt.Dimension(50, 32767));
        Hotel_InfoBox3.setMinimumSize(new java.awt.Dimension(645, 127));
        Hotel_InfoBox3.setPreferredSize(new java.awt.Dimension(645, 127));
        Hotel_InfoBox3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EliminarBtn3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarBtn3.setText("Eliminar");
        EliminarBtn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EliminarBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtn3ActionPerformed(evt);
            }
        });
        Hotel_InfoBox3.add(EliminarBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 75, 50));

        ModificarBtn3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarBtn3.setText("Modificar");
        ModificarBtn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ModificarBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtn3ActionPerformed(evt);
            }
        });
        Hotel_InfoBox3.add(ModificarBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 75, 50));

        Hotel_Pic3.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_Pic3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Hotel_Pic3.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic3.setText("Pic");
        Hotel_Pic3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox3.add(Hotel_Pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        EmailHotelTP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EmailHotelTP2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EmailHotelTP2.setForeground(new java.awt.Color(153, 153, 153));
        EmailHotelTP2.setText("hotel@site.com");
        jScrollPane11.setViewportView(EmailHotelTP2);

        Hotel_InfoBox3.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        TelefonoHotelTP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        TelefonoHotelTP2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TelefonoHotelTP2.setForeground(new java.awt.Color(153, 153, 153));
        TelefonoHotelTP2.setText("0412-1234567");
        jScrollPane12.setViewportView(TelefonoHotelTP2);

        Hotel_InfoBox3.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreHotelTP4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreHotelTP4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreHotelTP4.setText("Nombre");
        NombreHotelTP4.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane13.setViewportView(NombreHotelTP4);

        Hotel_InfoBox3.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        jTextPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jTextPane4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextPane4.setText("Descripcion");
        jScrollPane14.setViewportView(jTextPane4);

        Hotel_InfoBox3.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        Hotel_InfoBox1.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox1.setAutoscrolls(true);
        Hotel_InfoBox1.setMaximumSize(new java.awt.Dimension(50, 32767));
        Hotel_InfoBox1.setMinimumSize(new java.awt.Dimension(645, 127));
        Hotel_InfoBox1.setPreferredSize(new java.awt.Dimension(645, 134));
        Hotel_InfoBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EliminarBtn1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarBtn1.setText("Eliminar");
        EliminarBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EliminarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtn1ActionPerformed(evt);
            }
        });
        Hotel_InfoBox1.add(EliminarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 75, 50));

        ModificarBtn1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarBtn1.setText("Modificar");
        ModificarBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ModificarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtn1ActionPerformed(evt);
            }
        });
        Hotel_InfoBox1.add(ModificarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 75, 50));

        Hotel_Pic1.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_Pic1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Hotel_Pic1.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic1.setText("Pic");
        Hotel_Pic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox1.add(Hotel_Pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        EmailHotelTP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EmailHotelTP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EmailHotelTP.setForeground(new java.awt.Color(153, 153, 153));
        EmailHotelTP.setText("hotel@site.com");
        jScrollPane3.setViewportView(EmailHotelTP);

        Hotel_InfoBox1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        TelefonoHotelTP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        TelefonoHotelTP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TelefonoHotelTP.setForeground(new java.awt.Color(153, 153, 153));
        TelefonoHotelTP.setText("0412-1234567");
        jScrollPane4.setViewportView(TelefonoHotelTP);

        Hotel_InfoBox1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreHotelTP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreHotelTP2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreHotelTP2.setText("Nombre");
        NombreHotelTP2.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane5.setViewportView(NombreHotelTP2);

        Hotel_InfoBox1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        jTextPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jTextPane2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextPane2.setText("Descripcion");
        jScrollPane6.setViewportView(jTextPane2);

        Hotel_InfoBox1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        Hotel_InfoBox2.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_InfoBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox2.setAutoscrolls(true);
        Hotel_InfoBox2.setMaximumSize(new java.awt.Dimension(50, 32767));
        Hotel_InfoBox2.setMinimumSize(new java.awt.Dimension(645, 127));
        Hotel_InfoBox2.setPreferredSize(new java.awt.Dimension(645, 127));
        Hotel_InfoBox2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EliminarBtn2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarBtn2.setText("Eliminar");
        EliminarBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EliminarBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtn2ActionPerformed(evt);
            }
        });
        Hotel_InfoBox2.add(EliminarBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 75, 50));

        ModificarBtn2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarBtn2.setText("Modificar");
        ModificarBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        ModificarBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtn2ActionPerformed(evt);
            }
        });
        Hotel_InfoBox2.add(ModificarBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 75, 50));

        Hotel_Pic2.setBackground(new java.awt.Color(204, 255, 255));
        Hotel_Pic2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Hotel_Pic2.setForeground(new java.awt.Color(153, 153, 153));
        Hotel_Pic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotel_Pic2.setText("Pic");
        Hotel_Pic2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        Hotel_InfoBox2.add(Hotel_Pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 100, 120));

        EmailHotelTP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        EmailHotelTP1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EmailHotelTP1.setForeground(new java.awt.Color(153, 153, 153));
        EmailHotelTP1.setText("hotel@site.com");
        jScrollPane7.setViewportView(EmailHotelTP1);

        Hotel_InfoBox2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        TelefonoHotelTP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        TelefonoHotelTP1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TelefonoHotelTP1.setForeground(new java.awt.Color(153, 153, 153));
        TelefonoHotelTP1.setText("0412-1234567");
        jScrollPane8.setViewportView(TelefonoHotelTP1);

        Hotel_InfoBox2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 90, -1));

        NombreHotelTP3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        NombreHotelTP3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreHotelTP3.setText("Nombre");
        NombreHotelTP3.setPreferredSize(new java.awt.Dimension(20, 17));
        jScrollPane9.setViewportView(NombreHotelTP3);

        Hotel_InfoBox2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        jTextPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jTextPane3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextPane3.setText("Descripcion");
        jScrollPane10.setViewportView(jTextPane3);

        Hotel_InfoBox2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 94));

        javax.swing.GroupLayout ScrollBoxLayout = new javax.swing.GroupLayout(ScrollBox);
        ScrollBox.setLayout(ScrollBoxLayout);
        ScrollBoxLayout.setHorizontalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addComponent(Hotel_InfoBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Hotel_InfoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Hotel_InfoBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ScrollBoxLayout.setVerticalGroup(
            ScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollBoxLayout.createSequentialGroup()
                .addComponent(Hotel_InfoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hotel_InfoBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        Scroll_BGPanel.add(ScrollBox);

        jScrollPane1.setViewportView(Scroll_BGPanel);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(BuscadorCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BuscadorCiudad)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(CiudadesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 482));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorCiudadActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void EliminarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarBtn1ActionPerformed

    private void ModificarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarBtn1ActionPerformed

    private void EliminarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarBtn2ActionPerformed

    private void ModificarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarBtn2ActionPerformed

    private void EliminarBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarBtn3ActionPerformed

    private void ModificarBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BienvenidoMensage;
    private javax.swing.JTextField BuscadorCiudad;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JLabel CiudadesDisponibles;
    private javax.swing.JButton EliminarBtn1;
    private javax.swing.JButton EliminarBtn2;
    private javax.swing.JButton EliminarBtn3;
    private javax.swing.JTextPane EmailHotelTP;
    private javax.swing.JTextPane EmailHotelTP1;
    private javax.swing.JTextPane EmailHotelTP2;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Hotel_InfoBox1;
    private javax.swing.JPanel Hotel_InfoBox2;
    private javax.swing.JPanel Hotel_InfoBox3;
    private javax.swing.JLabel Hotel_Pic1;
    private javax.swing.JLabel Hotel_Pic2;
    private javax.swing.JLabel Hotel_Pic3;
    private javax.swing.JButton ModificarBtn1;
    private javax.swing.JButton ModificarBtn2;
    private javax.swing.JButton ModificarBtn3;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JTextPane NombreHotelTP2;
    private javax.swing.JTextPane NombreHotelTP3;
    private javax.swing.JTextPane NombreHotelTP4;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel ScrollBox;
    private javax.swing.JPanel Scroll_BGPanel;
    private javax.swing.JTextPane TelefonoHotelTP;
    private javax.swing.JTextPane TelefonoHotelTP1;
    private javax.swing.JTextPane TelefonoHotelTP2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
