/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Juan
 */
public class V_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public V_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        HeaderInicio = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        EntrarBtn = new javax.swing.JButton();
        RegistarseBtn = new javax.swing.JButton();
        Img_hotel = new javax.swing.JLabel();
        Img_Hotel2 = new javax.swing.JLabel();
        ReservarBtn = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderInicio.setBackground(new java.awt.Color(204, 255, 255));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText("123 Viajes C.A");

        EntrarBtn.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        EntrarBtn.setText("Entrar");
        EntrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarBtnActionPerformed(evt);
            }
        });

        RegistarseBtn.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        RegistarseBtn.setText("Registrarse");

        javax.swing.GroupLayout HeaderInicioLayout = new javax.swing.GroupLayout(HeaderInicio);
        HeaderInicio.setLayout(HeaderInicioLayout);
        HeaderInicioLayout.setHorizontalGroup(
            HeaderInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(RegistarseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntrarBtn)
                .addContainerGap())
        );
        HeaderInicioLayout.setVerticalGroup(
            HeaderInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addComponent(EntrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(RegistarseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(HeaderInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        Img_hotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel1.jpeg"))); // NOI18N
        Img_hotel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Background.add(Img_hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 250, 130));

        Img_Hotel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel2.jpeg"))); // NOI18N
        Img_Hotel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Background.add(Img_Hotel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 130));

        ReservarBtn.setBackground(new java.awt.Color(153, 255, 255));
        ReservarBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ReservarBtn.setForeground(new java.awt.Color(51, 51, 255));
        ReservarBtn.setText("¡¡Reserva ya!!");
        ReservarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ReservarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBtnActionPerformed(evt);
            }
        });
        Background.add(ReservarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 250, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("¡¡¡Suscribete, reserva  y disfruta de unas maravillosas vacaciones!!!");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAlignmentX(1.0F);
        jTextArea1.setAlignmentY(1.0F);
        Background.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 420, 50));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Para pasar las mejores vacaciones en familia navega en nuestra plataforma y encuentra los mejores hoteles y playas.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setAlignmentX(1.0F);
        jTextArea3.setAlignmentY(1.0F);
        Background.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, 80));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(1);
        jTextArea2.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(20);
        jTextArea2.setTabSize(20);
        jTextArea2.setText("Para pasar las mejores vacaciones en familia navega en nuestra plataforma y encuentra los mejores hoteles y playas.");
        jTextArea2.setMaximumSize(new java.awt.Dimension(32125, 32125));
        jTextArea2.setMinimumSize(new java.awt.Dimension(32125, 1856));
        Background.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 260, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservarBtnActionPerformed

    private void EntrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton EntrarBtn;
    private javax.swing.JPanel HeaderInicio;
    private javax.swing.JLabel Img_Hotel2;
    private javax.swing.JLabel Img_hotel;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JButton RegistarseBtn;
    private javax.swing.JButton ReservarBtn;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
