/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author usuario
 */
public class V_Pago extends javax.swing.JFrame {

    /**
     * Creates new form V_Pago
     */
    public V_Pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoPagoBtnGroup = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        NombreApp = new javax.swing.JLabel();
        BienvenidoMensage = new javax.swing.JLabel();
        Perfil = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ProfilePic = new javax.swing.JLabel();
        BG_Panel = new javax.swing.JPanel();
        FormPago = new javax.swing.JPanel();
        PagarBtn = new javax.swing.JButton();
        NumTarjetaLabel = new javax.swing.JLabel();
        TipoPagoLabel = new javax.swing.JLabel();
        VencimientoLabel = new javax.swing.JLabel();
        CSCLabel = new javax.swing.JLabel();
        CodigoPostalLabel = new javax.swing.JLabel();
        CiudadLabel = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        VencimientoField = new javax.swing.JFormattedTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        CiudadField = new javax.swing.JTextField();
        CSCField = new javax.swing.JFormattedTextField();
        TelefonoField = new javax.swing.JFormattedTextField();
        EmailField = new javax.swing.JFormattedTextField();
        CodigoPostalField = new javax.swing.JFormattedTextField();
        NumTarjetaField = new javax.swing.JFormattedTextField();
        Image = new javax.swing.JPanel();
        ProcederPagoLabel = new javax.swing.JLabel();
        RegresarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("123 Viajes C.A.");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(204, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(720, 80));

        NombreApp.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        NombreApp.setText(" 123 Viajes C.A");

        BienvenidoMensage.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BienvenidoMensage.setText("Bienvenido/a");

        Perfil.setBackground(new java.awt.Color(153, 255, 255));
        Perfil.setMnemonic('3');
        Perfil.setText("Perfil");
        Perfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 255), null));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 255, 255));
        Salir.setMnemonic('3');
        Salir.setText("Salir");
        Salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 255), null));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setText("ProfilePic");
        ProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(NombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(Perfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(BienvenidoMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Perfil)
                            .addComponent(Salir)))
                    .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BG_Panel.setBackground(new java.awt.Color(255, 255, 255));

        PagarBtn.setBackground(new java.awt.Color(204, 255, 204));
        PagarBtn.setText("Pagar");
        PagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarBtnActionPerformed(evt);
            }
        });

        NumTarjetaLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NumTarjetaLabel.setLabelFor(NumTarjetaField);
        NumTarjetaLabel.setText("Numero de tarjeta");

        TipoPagoLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TipoPagoLabel.setText("Tipo de pago");

        VencimientoLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        VencimientoLabel.setLabelFor(VencimientoField);
        VencimientoLabel.setText("Fecha de vencimiento");

        CSCLabel.setLabelFor(CSCField);
        CSCLabel.setText("CSC");

        CodigoPostalLabel.setLabelFor(CodigoPostalField);
        CodigoPostalLabel.setText("Codigo postal");

        CiudadLabel.setLabelFor(CiudadField);
        CiudadLabel.setText("Ciudad");

        TelefonoLabel.setLabelFor(TelefonoField);
        TelefonoLabel.setText("Telefono");

        EmailLabel.setLabelFor(EmailField);
        EmailLabel.setText("Email");

        VencimientoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/YYYY"))));
        VencimientoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VencimientoFieldActionPerformed(evt);
            }
        });

        TipoPagoBtnGroup.add(jRadioButton1);
        jRadioButton1.setText("Visa");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        TipoPagoBtnGroup.add(jRadioButton2);
        jRadioButton2.setText("MasterCard");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        CSCField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        TelefonoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout FormPagoLayout = new javax.swing.GroupLayout(FormPago);
        FormPago.setLayout(FormPagoLayout);
        FormPagoLayout.setHorizontalGroup(
            FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPagoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumTarjetaLabel)
                    .addComponent(TipoPagoLabel)
                    .addComponent(VencimientoLabel)
                    .addComponent(CSCLabel)
                    .addComponent(CodigoPostalLabel)
                    .addComponent(CiudadLabel)
                    .addComponent(TelefonoLabel)
                    .addComponent(EmailLabel))
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPagoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VencimientoField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FormPagoLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPagoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CSCField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addComponent(CiudadField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TelefonoField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CodigoPostalField))
                            .addComponent(NumTarjetaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormPagoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(PagarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        FormPagoLayout.setVerticalGroup(
            FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormPagoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumTarjetaLabel)
                    .addComponent(NumTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TipoPagoLabel)
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VencimientoLabel)
                    .addComponent(VencimientoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CSCLabel)
                    .addComponent(CSCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoPostalLabel)
                    .addComponent(CodigoPostalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CiudadLabel)
                    .addComponent(CiudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoLabel)
                    .addComponent(TelefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addGap(54, 54, 54)
                .addComponent(PagarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout ImageLayout = new javax.swing.GroupLayout(Image);
        Image.setLayout(ImageLayout);
        ImageLayout.setHorizontalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        ImageLayout.setVerticalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        ProcederPagoLabel.setText("Proceda con el pago");

        RegresarBtn.setBackground(new java.awt.Color(255, 204, 204));
        RegresarBtn.setText("Regresar");
        RegresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BG_PanelLayout = new javax.swing.GroupLayout(BG_Panel);
        BG_Panel.setLayout(BG_PanelLayout);
        BG_PanelLayout.setHorizontalGroup(
            BG_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BG_PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BG_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ProcederPagoLabel)
                    .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BG_PanelLayout.createSequentialGroup()
                        .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(29, 29, 29)
                .addComponent(FormPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        BG_PanelLayout.setVerticalGroup(
            BG_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BG_PanelLayout.createSequentialGroup()
                .addGroup(BG_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BG_PanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(ProcederPagoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(BG_PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FormPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );

        getContentPane().add(BG_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagarBtnActionPerformed

    private void VencimientoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VencimientoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VencimientoFieldActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarBtnActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_Panel;
    private javax.swing.JLabel BienvenidoMensage;
    private javax.swing.JFormattedTextField CSCField;
    private javax.swing.JLabel CSCLabel;
    private javax.swing.JTextField CiudadField;
    private javax.swing.JLabel CiudadLabel;
    private javax.swing.JFormattedTextField CodigoPostalField;
    private javax.swing.JLabel CodigoPostalLabel;
    private javax.swing.JFormattedTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel FormPago;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Image;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JFormattedTextField NumTarjetaField;
    private javax.swing.JLabel NumTarjetaLabel;
    private javax.swing.JButton PagarBtn;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel ProcederPagoLabel;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JButton RegresarBtn;
    private javax.swing.JButton Salir;
    private javax.swing.JFormattedTextField TelefonoField;
    private javax.swing.JLabel TelefonoLabel;
    private javax.swing.ButtonGroup TipoPagoBtnGroup;
    private javax.swing.JLabel TipoPagoLabel;
    private javax.swing.JFormattedTextField VencimientoField;
    private javax.swing.JLabel VencimientoLabel;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
